[package]
name = "mac-usb-test"
version = "0.1.0"
authors = ["luojia65 <me@luojia.cc>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "*"
core-foundation = "*"
mach = "*"
